runtime: python38 # or another supported version

instance_class: F1

env_variables:
  MYSQL_USER: 'root'              # please put in your credentials
  MYSQL_PASSWORD: 'TBD1234'       # please put in your credentials
  MYSQL_DB: 'covid19'             # please put in your credentials
  MYSQL_HOST: 34.172.3.217        # please put in your credentials

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles